version: '3'

services:
    frontend:
        container_name: frontend
        build: "frontend/."
        volumes:
          - './frontend:/app'
          - '/app/node_modules'
        ports:
          - '3000:3000'
    backend:
        container_name: backend
        build: "backend/."
        volumes:
          - "./backend:/code"
        ports:
          - "5000:5000"
        environment:
          - MODE=dev
        command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
        #command: gunicorn -c gunicorn.conf.py --logger-class=app.log_config.UniformLogger app.main:app
    nginx:
        container_name: nginx
        volumes:
          - "./nginx:/etc/nginx/conf.d"
        build: ./nginx
        ports:
          - 80:80
        depends_on:
          - backend
          - frontend
    db:
        container_name: postgres
        image: postgres
        restart: always
        environment:
          - POSTGRES_PASSWORD=postgres
    redis:
        container_name: redis
        image: "redis:alpine"
        ports:
          - "6379:6379"