FROM node:14-alpine
# 設置項目目錄
WORKDIR /app
# 安裝項目依賴
COPY package*.json /app/

RUN npm config set unsafe-perm true

RUN npm install --force

COPY . /app

RUN chown -R node:node /app/node_modules

USER node
# 運行
CMD ["npm", "run", "dev"]
